require: rubocop-rspec

AllCops:
  DisplayStyleGuide: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
