AllCops:
  DisplayStyleGuide: true

Style/IndentArray:
  EnforcedStyle: consistent

Metrics/ClassLength:
  CountComments: false
  Max: 250

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
